config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#rundown'
  devise_for :users

  resources :users, :outlets, :comments
  get 'static_pages/rundown'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :outlet
  has_many :children, class_name: "Comment", foreign_key: "parent_id"

  validates :body, :user, :outlet, presence: true
  validates :body, length: { in: 1..1000 }
end

app/models/outlet.rb
class Outlet < ApplicationRecord
  ALLOWED_CATEGORIES = ["vent", "rant", "qualm"].freeze

  belongs_to :user
  has_many :comments

  validates :category, :title, :body, :urgency, :user, presence: true
  validates :title, length: { in: 1..60 }
  validates :body, length: { in: 1..1000 }
  validates :urgency, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
  validates :category, inclusion: { in: ALLOWED_CATEGORIES }
end

app/models/user.rb
class User < ApplicationRecord
	has_many :outlets
	has_many :comments
	
	validates :username, :email, :encrypted_password, presence: true
	validates :username, :email, uniqueness: true
	validates :password, length: { in: 5..30 }
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@outlet = Outlet.find(params[:outlet_id])
		@comments = @outlet.comments.all
	end

	def new
		@comment = Comment.new
		@outlet = Outlet.find(params[:outlet_id])
		@user = current_user
	end

	def create
		@outlet = Outlet.find(params[:comment][:outlet_id])
		@comment = @outlet.comments.build(comment_params)
		@comment.user_id = params[:comment][:user_id]
		

		if @comment.save
			redirect_to(@outlet)
		else
			render "new"
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])

		if @comment.update(comment_params)
			redirect_to @comment.outlet
		end
	end

	def destroy
		@comment = Comment.find(params[:id])

		if @comment.destroy
			redirect_to @comment.outlet
		end
	end


	private
	def comment_params
		params.require(:comment).permit(:body, :outlet, :user, :parent_id)
	end
end

app/controllers/outlets_controller.rb
class OutletsController < ApplicationController

	def index
		@outlets = params[:category] ? Outlet.where(category: params[:category]) : Outlet.all
	end

	def new
		@outlet = Outlet.new
	end

	def create
		@user = current_user
		@outlet = @user.outlets.build(outlet_params)

		if @outlet.save
			redirect_to @user
		else
			render 'new'
		end
	end

	def show
		@outlet = Outlet.find(params[:id])
	end

	def edit
		@outlet = Outlet.find(params[:id])
	end

	def update
		@outlet = Outlet.find(params[:id])

		if @outlet.update(outlet_params)
			redirect_to(@outlet)
		else
			render 'edit'
		end
	end

	def destroy
		@outlet = Outlet.find(params[:id])

		if @outlet.destroy
			redirect_to @outlet.user
		end
	end

	private

	def outlet_params
		params.require(:outlet).permit(:category, :title, :body, :urgency, :user)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def rundown
		@valid_outlets = Outlet::ALLOWED_CATEGORIES
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to(@user)
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@user_outlets = params[:category] ? @user.outlets.where(category: params[:category]) : @user.outlets.all.order(created_at: :desc)							
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to(@user)
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])

		if @user.destroy
			redirect_to users_path
		end
	end


	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/outlets_helper.rb
module OutletsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<% @outlet.comments.each do |comment| %>
	<p><%= simple_format(comment.body) %></p>
<% end %>

app/views/comments/new.html.erb
<div class="form-container container col-md-8 col-md-offset-2">
	<%= form_for @comment, html: {class: "new-comment-form"} do |f| %>
			<%= f.hidden_field :outlet_id, value: @outlet.id %>
			<%= f.hidden_field :user_id, value: current_user.id %>
		
			<div class="row form-row comment-body-container col-md-12">
				<%= f.label :body, "Comment" %>
				<%= f.text_area :body, size: "60x6", placeholder: "Tell them how you really feel...", class: "form-control" %>
			</div>

			<div class="row form-row col-md-12">
				<%= f.submit "Submit", id: "comment-submit-button", class: "btn btn-success" %>
			</div>
	<% end %>
</div>

app/views/descriptions/_qualm.html.erb
<p id="qualm" class="outlet-description"> - This is what a qualm is all about</p>

app/views/descriptions/_rant.html.erb
<p id="rant" class="outlet-description rant"> - This is what a rant is all about</p>

app/views/descriptions/_vent.html.erb
<p id="vent" class="outlet-description vent"> - This is what a vent is all about</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeastMode</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container navbar-container">
	  	<nav class="navbar navbar-inverse col-md-12">
	  		<div class="fluid-container">
	  			<div class="navbar-header">
	  				<a class="navbar-brand" href="#">C-Mar</a>
	  			</div>
	  			<ul class="nav navbar-nav">
	  				<li class="nav-item"><%= link_to "Rundown", static_pages_rundown_path %></li>
	  			</ul>

	  			<ul class="nav navbar-nav header-middle">
	  				<li class="nav-item header-title">Melon Juice</li>
	  			</ul>

	  			<ul class="nav navbar-nav navbar-right right-nav">
	  				<% if signed_in? %>
	  					<li class="nav-item"><%= link_to "Profile", user_path(current_user) %></li>
	  					<li class="nav-item"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	  				<% else %>
	  					<li class="nav-item"><%= link_to "Log In", new_user_session_path %></li>
	  				<% end %>	
	  			</ul>
	  		</div>
	  	</nav>
	</div>
    <%= yield %>
  </body>
</html>

app/views/outlets/edit.html.erb
<div class="form-container container col-md-8 col-md-offset-2">
	<%= form_for @outlet, url: {action: "update"}, html: {class: "new-outlet-form"} do |f| %>
		
			<div class="row form-row title-container col-md-7">
				<%= f.label :title, "Title" %>
				<%= f.text_field :title, placeholder: "Outlet Title", class: "form-control" %>
			</div>

			<div class="row form-row outlet-menu-container col-md-3 ">
				<%= f.select("category", options_for_select([['qualm', 'qualm'], ['vent', 'vent'], ['rant', 'rant']]), { prompt: "Outlet Type"}, class: "form-control dropdown-toggle outlet-dropdown col-md-12")  %>
			</div>

			<div class="row form-row outlet-urgency-container col-md-2  ">
				<%= f.select("urgency", options_for_select([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]]), { prompt: "Urgency"}, class: "form-control select-picker urgency-dropdown col-md-12")  %>
			</div>

			<div class="row form-row body-container col-md-12">
				<%= f.label :body, 'Outlet' %>
				<%= f.text_area :body, size:"60x12", placeholder: "Let it out...", class: "form-control" %>
			</div>
			
			<div class="row form-row col-md-12">
				<%= f.submit "Update Your Expression", class: "btn btn-success" %>
			</div>
	<% end %>
</div>

app/views/outlets/index.html.erb
<% @outlets.each do |outlet| %>
	<h4><%= outlet.title %></h4>
	<p><%= outlet.body %><p>
<% end %>

app/views/outlets/new.html.erb
<div class="form-container container col-md-8 col-md-offset-2">
	<%= form_for @outlet, url: {action: "create"}, html: {class: "new-outlet-form"} do |f| %>
		
			<div class="row form-row title-container col-md-7">
				<%= f.label :title, "Title" %>
				<%= f.text_field :title, placeholder: "Outlet Title", class: "form-control" %>
			</div>

			<div class="row form-row outlet-menu-container col-md-3 ">
				<%= f.select("category", options_for_select([['qualm', 'qualm'], ['vent', 'vent'], ['rant', 'rant']]), { prompt: "Outlet Type"}, class: "form-control dropdown-toggle outlet-dropdown col-md-12")  %>
			</div>

			<div class="row form-row outlet-urgency-container col-md-2  ">
				<%= f.select("urgency", options_for_select([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]]), { prompt: "Urgency"}, class: "form-control select-picker urgency-dropdown col-md-12")  %>
			</div>

			<div class="row form-row body-container col-md-12">
				<%= f.label :body, 'Outlet' %>
				<%= f.text_area :body, size:"60x12", placeholder: "Let it out...", class: "form-control" %>
			</div>
			
			<div class="row form-row col-md-12">
				<%= f.submit "Express Yourself", class: "btn btn-success" %>
			</div>
	<% end %>
</div>

app/views/static_pages/rundown.html.erb
<div class="jumbotron rundown-jumbotron col-md-8 col-md-offset-2">
	<h2 class="rundown-heading">Learn more about all the available outlets<br>
	you can use to epxress yourself<br>
	or</h2>
	<%= button_to "Create Your Own", new_outlet_path, method: :get, class: "btn btn-primary create-button" %>
</div>

<div class="outlet-info-container col-md-8 col-md-offset-2">
	<h3 class="outlet-info-heading">See which outlet will best fit your feelings</h3>
		<div class="outlet-dropdown-container">
			<button class="btn btn-info dropdown-toggle outlet-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Outlets <span class="caret"></span></button>
				<ul class="dropdown-menu">
					<% @valid_outlets.sort.each do |valid_outlet| %>
			    		<li class="outlet-info-link"><a id=<%= "#{valid_outlet}" + "-info-link" %> href=#<%= "#{valid_outlet}" + "-heading" %> ><%= "#{valid_outlet}" %></a></li>
			    	<% end %>
		  		</ul>
		</div>
</div>

<div class="container col-md-8 col-md-offset-2">
	<% @valid_outlets.sort.each do |valid_outlet| %>
		<div class="row outlet-row col-md-12">
			<h2 class="outlet-name"><%= link_to valid_outlet, outlets_path(category: valid_outlet), id: "#{valid_outlet}" + "-heading" %></h2>
			<%= render "descriptions/#{valid_outlet}" %>
		</div>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="user-container row">
	<div class="user-info-box col-md-2 col-md-offset-2">
		<div class="user-username"><h2> <%= @user.email %> </h2></div>
		<div class="user-middle"><span class="glyphicon glyphicon-user"></span></div>
		<div class="user-bio"><p>This is my amazing quote that describes me so well</p></div>
	</div>
	<div class="outlet-bar-container col-md-6 col-md-offset-1">
		<div class="top-bar">
			<h5 class="top-bar-title">Starting to feel something..?</h5>
			<div class="btn-group create-outlet-buttons" role="group">
				<%= button_to "Create Your Own Outlet", new_outlet_path, method: :get, id: "create-outlet-button", class: "btn btn-primary create-outlet-button" %>
			</div>
		</div>

		<div class="bottom-bar">
			<h5 class="bottom-bar-title">Check out how <%= @user.email %> has been feeling</h5>
			<div class="btn-group user-outlet-buttons" role="group">
				<%= link_to "Newest Outlets", user_path(@user), id: "newest-outlet-button", class: "btn btn-primary user-outlet-option", role: "button" %>
				<%= link_to "Vents", user_path(@user, category: "vent"), id: "user-vent-button", class: "btn btn-info user-outlet-option", role: "button" %>
				<%= link_to "Rants", user_path(@user, category: "rant"), id: "user-rant-button", class: "btn btn-warning user-outlet-option", role: "button" %>
				<%= link_to "Qualms", user_path(@user, category: "qualm"), id: "user-qualm-button", class: "btn btn-danger user-outlet-option", role: "button" %>
			</div>
		</div>
	</div>
</div>



<div class="container user-outlets-container col-md-7 col-md-offset-5">
	<% if @user_outlets %>
		<% @user_outlets.each do |outlet| %>
			<div class="user-outlet row <%= outlet.category %> col-md-11">
				<div class="outlet-head col-md-12">
					<h6 class="outlet-category col-md-2"> <%= outlet.category.capitalize %> </h6>
					<h3 class="outlet-title col-md-8"><%= outlet.title %></h3>
					<h6 class="outlet-urgency col-md-2">Urgency: <%= outlet.urgency%> </h6>
					<h6 class="outlet-posted-at">Posted: <%= outlet.created_at.strftime("%B %e, %Y") %></h6>
				</div>

				<div class="outlet-body col-md-12">
					<%= outlet.body %>
				</div>

				<div class="outlet-bottom-bar col-md-12">
					<div class="outlet-comment-buttons col-md-6">
						<%= link_to "Comment", new_comment_path(outlet_id: outlet.id), id: "create-outlet-comment-button", class: "btn btn-success outlet-comment-button glyphicon glyphicon-pencil", role: "button" %>
						<%= link_to "All Comments (#{outlet.comments.count})", comments_path(outlet_id: outlet.id), id: "view-outlet-comments-button", class: "btn btn-primary outlet-comment-button", role: "button" %>
					</div>
					<div class="outlet-option-buttons col-md-6">
						<%= link_to "Delete", outlet_path(outlet), data: {:confirm => 'Are you sure?'}, method: :delete, id: "delete-outlet-button", class: "glyphicon glyphicon-trash btn btn-danger outlet-option-button", role: "button" %>
						<%= link_to 'Edit', edit_outlet_path(outlet), id: "edit-outlet-button", class: "btn btn-primary glyphicon glyphicon-edit outlet-option-button", role: "button" %>
					</div>
				</div>

			</div>
		<% end %>
	<% else %>
		<p>This user does not have any outlets... yet</p>
	<% end %>
</div>